name: Playwright Tests
on:
  pull_request:
    branches:
      - develop

jobs:
  linux:
    name: ${{ matrix.os }} E2E
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        nodeversion: ['16.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          cache: npm
          node-version: ${{ matrix.nodeversion }}
      - name: Cache node modules
        if: ${{ !env.ACT }}
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup custom host for sdkapp.example.com
        run: echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" | sudo tee -a /etc/hosts
      - name: Install NPM
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm i -g npm@8
      - name: Install Dependencies
        run: npm ci
        env:
          DEBUG: pw:install
      - name: Build SDK
        run: npm run build
      - name: Install Playwright
        run: npx playwright install-deps
      - name: Run e2e
        run: npm run test:e2e
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
  osx:
    name: ${{ matrix.os }} E2E
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0]
        nodeversion: ['16.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Cache node modules
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup custom host for sdkapp.example.com
        run: echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" | sudo tee -a /etc/hosts
      - name: Install NPM
        run: npm i -g npm@8
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          DEBUG: pw:install
      - name: Install Playwright
        run: npx playwright install-deps
      - run: npm run build
      - run: npm run test:e2e
  windows:
    name: ${{ matrix.os }} E2E
    strategy:
      fail-fast: false
      matrix:
        nodeversion: ['16.x']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Setup custom host for sdkapp.example.com
        run: echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" >> C:\Windows\System32\drivers\etc\hosts #add to new line
      - name: debug etc hosts
        run: type C:\Windows\System32\drivers\etc\hosts
      - name: Install NPM
        run: npm i -g npm@7
      - name: Install Dependencies
        run: npm ci
        env:
          DEBUG: pw:install
      - name: Install Playwright
        run: npx playwright install-deps
      - run: npm run build
      - run: npm run test:e2e
